version: "3"

services:
  app:
    build: .
    container_name: tcc-api
    volumes:
      - .:/home/python/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:12.2
    container_name: tcc-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tcc
    ports:
      - 5432:5432
